"""Add expenses table

Revision ID: 456f8772489f
Revises: 9d4b76a27e7a
Create Date: 2025-11-14 18:17:25.500095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '456f8772489f'
down_revision = '9d4b76a27e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livestock')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=False)

    op.create_table('livestock',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('animal_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('health_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.farm_id'], name=op.f('livestock_farm_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('livestock_pkey'))
    )
    # ### end Alembic commands ###
